sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  fast_finish: true
  include:
  - php: '7.2'

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

before_script:
  - phpenv rehash
  - composer install

script:
  - vendor/bin/phpunit
