sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  fast_finish: true
  include:
  - php: '7.2'

cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"

before_script:
  - composer install --no-interaction
  - cp .env.example .env
  - php artisan key:generate

script:
  - vendor/bin/phpunit
